drivers: muic: fix build error due to out-of-src build or gcc version
Not sure exactly what triggers it. Fixing so that the Kconfig and
Makefile's are setup properly solves the error, which looks like:

drivers/muic/universal/muic_state.c:363:1: fatal error: opening dependency file drivers/muic/universal/.muic_state.o.d: No such file or directory

This commit is basically the same as (part of)
https://github.com/jcadduono/android_kernel_samsung_universal3475/commit/8b34f9d012ccf836f6211fc7577d40f460402718

Change-Id: I2faffd4d0dbb94dcfba75f8be1c04f31941f1469