security: tima_uevent: fix build error due to out-of-src build or gcc version
Not sure exactly what triggers the error, but properly setting up
Makefiles and Kconfig for tima_uevent fixes it. Previously compilation
failed with:

security/tima_uevent/tima_uevent.c:217:1: fatal error: opening dependency file security/tima_uevent/.tima_uevent.o.d: No such file or directory
  217 | module_exit(tima_uevent_exit);
      | ^~~~~~~~~~~

This commit is basically the same as (part of)
https://github.com/jcadduono/android_kernel_samsung_universal3475/commit/8b34f9d012ccf836f6211fc7577d40f460402718

Change-Id: I8a7625c820df5e19b44567df12275cc90b8c862a